### ISSUE TITLE
Create a new product line & Skip SPLOT configuration

### ISSUE THREAD

**Issue by hamzawey** [onekin/GitLine#14]
Hi,
I wanted to create my own product line (core repository and product ones). How can i achieve that?

Thanks, 
Mostafa

**Comment by letimome** [comment]
Hi!

Do you have your own SPL developed? Which variability implementation you use?  
You may want to have a look at http://spl2go.cs.ovgu.de/ if you want an open SPL sample. Or fork my core asset repository from https://github.com/letimome/VODPlayer-CoreAssets. Take into account that GitLine works for feature-oriented SPLs, where feature implementations are modularized into the code assets (ideally a folder per feature).

To set up your own SPL:
1. Model your SPL feature diagram with SPLOT http://splot-research.org/  
![captura de pantalla 2016-04-14 a las 10 17 27](https://cloud.githubusercontent.com/assets/5872026/14521575/2c7a3df8-022a-11e6-9ccb-c5bc557015d1.png)
When you are done modeling it, click on "configure". It will pop up a window. Copy the URL of the pop-up window (you will need it later on). The URL would be something like "http://ec2-52-32-1-180.us-west-2.compute.amazonaws.com:8080/SPLOT/SplotConfigurationServlet...". 
2. To play yourself with GitLine, is best you have two github accounts. One for DE, to keep the core asset repository and another one for AE, to create a product repository.
3. Log in with your DE account. Create a new repository, named with patters <SPLName> -CoreAssets. In the master branch, you should have all your core assets. A folder per feature. I.e., If your SPL has 3 features (named f1,f2,f3) you should have three folders equally named. Inside each folder place the assets that implement the feature. Additionally, create a file named "splot-configurator-url". Paste here the URL to SPLOT configurator. The one on step1. Your core repo should look similar to mine: https://github.com/letimome/VODPlayer-CoreAssets
4. Now your core asset repo is ready.
5. Log in with the AE account. Access the core asset repository. You should see the "product Fork". If you click on it, the SPLOT configurator will show up in a frame, where you (as a AE) can select the features you want for your product repository. As depicted in http://letimome.github.io/GitLine/. When ready, click on "create product repository" and you will get a new product repository into you AE account. This repo, is initialized with a set of branches and the set of features you have selected. It also has a README with guidelines for product development.
6. From then on, you (as a DE) can update the core assets. To get these changes to the product repo, log in as a AE, checkout "update.update" branch, "Update propagation" will show up and click on it. Follow instruction at http://letimome.github.io/GitLine/ .
7. To  feedback a product-specific asset to the core asset repo, you need to follow a similar process. Check again http://letimome.github.io/GitLine/

Cheers,
Leticia

**Comment by hamzawey** [comment]
Thanks a lot Leticia for your updates. 
one more question, Is there a way to bypass SPLOT? In case I want my product lines private? 
Thanks, 
Mostafa

**Comment by letimome** [comment]
Hi Mostafa,

Give me some time to deliver the new functionality you request. 
Cheers,
Leticia

**Comment by hamzawey** [comment]
Thanks Leticia, 
I'm interested in the project too. Please let me know how can i help. 
Cheers, 
Mostafa

**Comment by letimome** [comment]
Good to know you are interested in GitLine :) 

You are welcome to Fork the project and then pull-request your developments to my repo. It may take you some time to understand how GitLine works... The functionality it is mainly developed in githubdeltas.js file: developed in JavaScript, I call the github API v3, and also make HTTP requests to github.com to accomplish Product Fork, and update propagation & Feedback Propagation.  

The function you are interested in (to skip SPLOT) is the following: InstallEController.prototype.execute=function(act). Calling function DeltaUtils.enactProductFork(ghUser, ghRepo, coreAssetIds), you enact productFork operation. CoreassetsIds being the list of coreAsset names (folder names) you want to initialized the product with.

If you want, you can have a try and develop it yourself. In any case, I was planning to have it developed for Friday, so you can wait a little bit :)

Do not hesitate to request more functionality to GitLine. You are welcome!

**Comment by letimome** [comment]
Hi Mostafa,

I just delivered a new version for GitLine.

The functionality I have develop, does the following:
1. When ProductFork is clicked, you can choose between "manual" or "splot" configuration.
2. Type manual to skip SPLOT based config. 
3. Then, you will have to type the core assets names (first-level folder names) you want to instantiate in you product repository.

That's it. I don't now if this functionality would suit your needs, as I am not aware of how you intend to use GitLine. 

By the way, I've read your publications :-) If you can send me more information on how you intend to use GitLine, maybe I could adapt it for your need. Feel free to email me at leticia.montalvillo@ehu.eus anytime, and let me know if we can somehow collaborate (without obligation).

Best,
Leticia

**Comment by hamzawey** [comment]
Thanks a lot Leticia,
